class Trial_1
{
    public static void main(String[] args) 
    {
        
        byte b1 = 24;
        char ch = 'A';
        short sh = 10;
        long lo = 100;
        int a = 10;
        float fl = 33.3f;
        double d = 43.21;
        
         /*
        Error: variable not initialized
        
        byte b;
        System.out.println("byte = " + b);
        */
        
        System.out.println("byte = " + b1);
        System.out.println("char = " + ch);
        System.out.println("short = " + sh);
        System.out.println("long = " + lo);
        System.out.println("int = " + a);
        System.out.println("float = " + fl);
        System.out.println("double = " + d);
        
    }
}